# https://github.com/bitnami/charts/blob/main/bitnami/mongodb/README.md
mongodb:
  replicaCount: 1

# https://github.com/bitnami/charts/blob/main/bitnami/redis/README.md
redis:
  replicaCount: 1

# https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/README.md
rabbitmq:
  replicaCount: 1

# https://github.com/bitnami/charts/blob/main/bitnami/minio/README.md
minio:

frontend:
  image: "ghcr.io/ecoma-io/internal-frontend"
  replicaCount: 1
  port: 4200
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 750m
      memory: 512Mi
  env: []
  ingress:
    host: ecoma.io

backend:
  image: "ghcr.io/ecoma-io/internal-backend"
  replicaCount: 1
  port: 3000
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 750m
      memory: 512Mi
  env: []
  ingress:
    host: api.ecoma.io
