/**
 * @type {import('typedoc').TypeDocOptions}
 */
module.exports = {
  // Sử dụng plugin Markdown
  plugin: ["typedoc-plugin-markdown"],

  // Chọn theme của plugin Markdown
  theme: "markdown",
  pageTitleTemplates: {
    module: (args) => `${args.kind}: ${args.name}`,
    member: (args) => `${args.kind}: ${args.name}`,
  },
  disableSources: true, // Tắt hiển thị mã nguồn trong tài liệu
  useTsLinkResolution: true, // Sử dụng TypeScript để giải quyết các liên kết trong tài liệu
  hideGenerator: true, // Ẩn thông tin "Generated by TypeDoc" ở cuối trang
  mergeReadme: true, // Gộp nội dung README.md vào đầu trang tài liệu
  flattenOutputFiles: true, // Làm phăng cấu trúc thư mục đầu ra, tất cả các file sẽ được lưu trong một thư mục duy nhất
  hidePageHeader: true, // Ẩn tiêu đề trang (có thể là tên module hoặc tên file)
  hideBreadcrumbs: true, // Ẩn breadcrumb (đường dẫn điều hướng) ở đầu trang
  useHTMLAnchors: true, // Sử dụng HTML anchors thay vì ID cho các liên kết trong tài liệu
};
