apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: ecoma
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ecoma
    app.kubernetes.io/component: backend
