apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: ecoma
    app.kubernetes.io/component: frontend
spec:
  rules:
    - host: {{ .Values.frontend.ingress.host | default "" }}
      http:
        paths:
          - path: {{ .Values.frontend.ingress.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
  tls:
    - hosts:
        - {{ .Values.frontend.ingress.host | default "" }}
      secretName: ecoma-frontend-tls