name: Delivery

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  delivery:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_BOT_TOKEN }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          INPUT_GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
        run: |
          if npx should-semantic-release; then
            /usr/bin/git config --global --add url."https://${{ secrets.GH_BOT_TOKEN }}:x-oauth-basic@github".insteadOf ssh://git@github
            /usr/bin/git config --global --add url."https://${{ secrets.GH_BOT_TOKEN }}:x-oauth-basic@github".insteadOf https://github
            /usr/bin/git config --global --add url."https://${{ secrets.GH_BOT_TOKEN }}:x-oauth-basic@github".insteadOf git@github
            /usr/bin/git config --global user.email "adm.ecoma@gmail.com"
            /usr/bin/git config --global user.name "EcomaIO (Bot)"


            version=$(npx release-it --release-version)
            echo "Release v$version"

            echo "::group::Publish packages"
            export VERSION=$version
            npx nx run-many -t publish
            echo "::endgroup::"

            echo "::group:: commit and push change"
            npx release-it -c .github/release.ts  --verbose
            echo "::endgroup::"
          else
            echo "No release needed"
          fi
